# Generated by Django 2.1 on 2018-08-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='abstract',
            field=models.CharField(default='adfasdfasdfasdfasdfasfdsafd', max_length=60),
            preserve_default=False,
        ),
    ]
